### ISSUE TITLE
For the zsh shell, some bits of the terminal are invisible

### ISSUE THREAD

**Issue by isheebo** [tourervit/phantom-vscode-theme#1]
I noticed that when working on a version-controlled project, the statement `git:(...)` disappears in the background for the **zsh** shell. I've attached screenshots for both this theme and the default `Dark+` theme just to give you context. 

A lighter colour for `git:(...)` would be appreciated. Otherwise thanks for the good work.

**With this theme**

<img width="486" alt="screen shot 2019-01-02 at 3 22 41 pm" src="https://user-images.githubusercontent.com/29917291/50592097-b293ce80-0ea3-11e9-9ab4-d97f2fbb8b72.png">

**With the Default Dark+ Theme**
<img width="977" alt="screen shot 2019-01-02 at 3 23 11 pm" src="https://user-images.githubusercontent.com/29917291/50592134-d9ea9b80-0ea3-11e9-9ba6-a928b08bd91e.png">

**Comment by tourervit** [comment]
Thank you for your feedback, would be fixed in a minute!
