### ISSUE TITLE
filename is invisible for inline git diffs.

### ISSUE THREAD

**Issue by isheebo** [tourervit/phantom-vscode-theme#2]
When viewing git diffs inline, the filename is barely visible. For context, from line 1000, the word `.rubocop.yml` which is the filename can barely be seen in *Phantom theme screenshot*.

Kindly let me know in case it is hard to replicate it. thank you
**Dark+ Theme**
![screen shot 2019-01-02 at 10 50 27 pm](https://user-images.githubusercontent.com/29917291/50609563-1ee0f300-0ee1-11e9-974e-b7a612e748ad.png)

**Phantom theme**
![screen shot 2019-01-02 at 10 51 12 pm](https://user-images.githubusercontent.com/29917291/50609577-2dc7a580-0ee1-11e9-8b41-1460d9e61c28.png)

**Comment by tourervit** [comment]
It would be helpful if you'd tell me what git diff key/options produces that issue in your case.

**Comment by isheebo** [comment]
To be able to replicate this, make changes to say, [this file](https://github.com/tourervit/phantom-vscode-theme/blob/master/themes/Phantom-color-theme.json) in your vscode locally. 

save the file, without adding the changes to git. you will see `yellow bars` appear to the left of the changes you made.

On clicking on any of the yellow/green bars, you should be able to see the diffs above. the bars are of the yellow/green color when using the Phantom theme.

I hope this helps
<img width="771" alt="screen shot 2019-01-03 at 10 56 31 am" src="https://user-images.githubusercontent.com/29917291/50627818-5d5cc900-0f46-11e9-9a65-f1177f81fb7a.png">

**Comment by tourervit** [comment]
Oh, now I see. That's because I have ```"git.enabled": false```, so... fixed!
